export const metadata = {
  title: "@steffy_jk_",
  description: "Generated by @steffyjk",
};

import "./globals.css";
import Navbar from "../components/Navbar";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}

